name: Keep Render App Alive

on:
  schedule:
    - cron: "2,7,12,17,22,27,32,37,42,47,52,57 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging Render app..."
          curl -L -v --fail --max-time 180 https://timetable-builder-lcfy.onrender.com
          echo "Ping successful"
